#+AUTHOR: Jeffrey Young
#+TITLE: Primer on Dan Hillman's Thesis
#+DATE: Mar 30, 2017

# Fix the margins
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{bussproofs}
#+LATEX_CMD: pdflatex

# Remove section numbers, no table of contents
#+OPTIONS: toc:nil
#+options: num:nil

# Set the article class
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [10pt, letterpaper]

* Context
  This document is for the XOP Encoding project, participants include Eric
  Walkingshaw and Jeffrey Young. This is the third such primer in the project,
  the first one is a primer on DN-Theory, the second a primer on typologies of
  explanation, specifically Bellack et al's typology. This document expands on
  bellack et al's typology by summarizing the thesis of Dan Hillman. Dan Hillman
  iterated on bellack's typology, changing and improving it in several ways, and
  hence his typology is of interest to the XOP project. Dan Hillman was also kind
  enough to provide the data he compiled with his typology for the XOP Project.
* Orientation
  This document is meant to explicate three things:
  1. What are Hillman's changes to Bellack's typology and why
  2. What is the nature of the data that Hillman compiled and it is useful to the
     XOP project?
  3. What did Hillman learn from his data, what were the conclusions of his
     thesis?
     
  The document assumes you are familiar with Bellack et al's typology, and the
  XOP Projects goals, progress, and current issues. If any of those is not the
  case then please refer to prior documents to orientate yourself before reading
  on.
* Executive Summary 
  Is Hillman's data suitable for our us: Yes. I believe we will be able to make
  use of his data, but we will not be able to say anything in regards to
  Substantive Meaning using this data. 

  Is Hillman's typology more expressive or less expressive than Bellack's,
  should we us Hillman's or Bellack's: We should use Hillman's Typology, in many
  ways it is a large improvement over Bellack's and his agreement rate is > 90%.
  We will need to modify his typology as he collapses the Substantive meaning
  category so that it /does not/ need to be described /for every/ topic.

  What did Hillman learn from his data: TBD, I ran out of time and didn't get to
  this.

* Details on Hillman's Data 

** General Details of the Data
   - Data is composed of Face-To-Face (FTF) and Computer-Mediated-Communication
     (CMC)
   - All data is from courses taught at New York School of Education between
     1994 - 1995
   - Data was recorded from 2 classes:
     1. Systems Analysis and Design
     2. Database Management and Systems
   - Both courses had FTF and CMC versions, and both versions taught the same material 
** Details on the Transcription of the Data 
   - FTF courses were recorded on audio cassette, transcribed to word docs, then
     munged into a database
   - Participants for CMC courses communicated, and were recorded, by Lotus Notes.
   - only interactions that encompassed /the whole class/ was included 
   - interactions during breaks were not considered or included 
   - Any small group discussions that took place were not considered or included 
   - No one working on the transcript, editing, or the coding, had knowledge of
     what was transcribed, which participant said it, or the purpose of the
     research 

** Database and data information details
*** Database Contains
    1. All text
    2. Participants sex
    3. Participants role (Teacher/Student)
    4. Number of words in each sentence
    5. Metadata of course (Course name, date etc.)
*** Data alterations
    - All audio recordings were pre-pended with a character to denote the speaker, one of:
      1. t \triangleq teacher
      2. m \triangleq male student
      3. f \triangleq female student
** Hillman's Problems with Bellack et al's typology
   Most of this is taken directly from Hillman's thesis:
   1. Problem: Bellack's system fails to differentiate between a one-word
      response and a one-liner response. This is consequent of Bellack et al's
      decision to round any non-line utterance to length 1.

      Effect: This gives unfair weight to utterances that are less than one-line
      length, which distorts the differences between teacher and student
      utterances (with the latter being inflated).
   2. Problem: Structuring and Soliciting moves fail to capture monologues or exegesis

      Effect: This constrains the systems unit of analysis, in fact, Hillman
      found that studies which employed Bellack's system, and Bellack et al's
      own data, have almost no monologues by the teacher, and are almost never
      have adult student participants - only children.
   3. Problem: The difference between Responding and Reacting moves is often
      minimal and the two are easily interchangable, especially in asynchronous
      communication (Bellack et al assumed synchronous communication e.g. a
      conversation)

      Effect: Superfluous encodings and noise in agreement rate
   4. Problem: Substantive meanings fail to account for progressive levels of
      meaning, which, in turn, make it difficult to code for any subject in
      which the same idea or procedures are used at higher levels. For example,
      in a math class one would learn multiplication or division not as an end
      in and of itself, but as part of a larger process. Bellack's system cannot
      account for this in a clean way.
   5. Problem: Substantive Meanings are not abstracted from the course material
      at all. In general, each substantive meaning is derived from the course
      material, but if that material differs slightly than the meanings must
      also change.
      
      Effect: Comparing courses on the same material or topic becomes more
      difficult
   6. Problem: Instructional Meanings are similarly limited
   7. Problem: Inclusion of an Audio-Video devices inflates its importance in
      the classroom interaction to that of the participant. 

      Effect: One cannot claim that if a teacher plays a move or audio snippet
      as part of the lesson that the student is interacting with the content in
      /an observable/ manner.
   8. Problem: Bellack et al's system does not distinguish between differences
      in students.

      Effect: One cannot analyze the variable of sex in the data.
   9. Problem: Bellack et al's system distinguishes between discussion that
      occurs "as the result of an assignment", and intra-classroom discourse.
      
      Effect: This excludes discourse which occurs from a teacher assigning work
      /and then/ building on that assignment in class.

* Hillman's modifications to Bellack's Typology
  Hillman's Typology consists of three Tiers with the first being Purpose:
** Purpose
   Pedagogical Moves are denoted by Purpose. Purpose has 7 Categories. Hillman
   describes Purpose as a highway. In order to use a highway, one must get
   directions to it, know the length of the journey, and the destination; these
   would correspond to orienting utterances. When on the Highway, one moves
   forward by the Lecturing purpose. A rest stop, to relax, recover, get gas or
   food would be a Humanizing purpose. And finally an off-ramp would be an
   Eliciting move, while an on-ramp would be a responding move. The exact
   definitions of each are as follows:

   1. Organizing: Similar to Structuring moves, organizing sentences do not
      elicit a response and are not responses. Organizing sentences set an
      agenda, organize a discussion or recitation, and function as a means to
      get to other Purposes. Hillman describes them as functioning similar to an
      on-ramp to a highway.

      Ex. "In a minute I'll be handing you an overview of the course as well as
      handouts for the first session." [Organising/Fact-Stating/Procedure]

   2. Eliciting: Similar to Soliciting moves. Eliciting moves consist of
      solicitations or explicit directives. They include all questions,
      commands, imperatives, and requisitions. They are specifically designed to
      cause interaction.
      
      Ex. "Send me a Response to Response if you have any questions concerning
      the basic forms creation process." [Eliciting/Performing/Procedure]

   3. Responding: Responding moves combine reacting and responding moves from
      Bellack's typology. They form a reciprocal relationship to _any_
      previously uttered move. In CMC courses, one may respond to a single word
      of the electronic lecture, or to the whole lecture, thus a responding move
      can "close" any previously uttered move, or moves. A responding move
      concludes when sentences cease to serve the function of directly
      responding to the previous moves.
      
      Ex. "Yeah I hear, I hear." [Responding/Rating/Person]

   4. Lecturing: Lecturing consists of talk about the course content that is
      neither explaining a change in topic (Organising), soliciting a response
      (Eliciting), nor Responding. Lecturing is differentiated from Responding
      in that Responding is directly applicable to an Eliciting purpose. When
      the Responding move has moved away from the purpose of merely answering
      the Eliciting, it is then Lecturing. For example, suppose a student asked
      a teacher what colour fire engines were. The immediate answer, "red" (or
      "fluorescent yellow-green") would be a Responding sentence, but anything
      beyond that, such as explaining why so many fire engines are red, would be
      Lecturing.

      Ex. "We went a little over tonight, but that's all right."
      [Lecturing/Fact-Stating/Content]

   5. Humanizing: Humanizing moves create an atmosphere conducive to interaction
      by means of making student feel welcome jokes or small talk. Humanizing
      moves' purpose is to make some feel at ease or maintain the relationship.
      These moves are free from pedagogic content. This type also includes the
      use of emoticons. Hillman speaks more to this latter use, it is not
      represented here.
      
      Ex. "You don't prefer to be called Jill?" [Humanising/Fact-Stating/Person]

   6. Idling: This category has no analogy to Bellack's typology, rather this is
      a pure addition. Idling sentences are sentences which are intelligible but
      serve no pedagogical function, and unlike Humanizing sentences have no
      defined goal e.g. to create a comforting environment. This type of move is
      included because it is a way for the teacher to pause and collect their
      thoughts.
      
      Ex. "That you, you know when you, oh no, no, no." [Idling/Filler/Not Clear]

   7. Not Clear: The bottom value for the Purpose tier. This is encoded when
      words are unintelligible. 
** Mechanism
   Mechanisms are similar to Instructional-Logical Meanings (Hillman uses
   Instructional-Logical meanings, but I think he means Substantive-Logical),
   they describe /how/ the subject of the sentence is being discussed. There are
   9 sub-categories:
   1. Fact-Stating: This is identical to Bellack et al.'s definition of
      Fact-Stating

   2. Explaining: This is a combination of Bellack et al.'s definitions of
      Interpreting, and Explaining. This is used for sentences in which
      clarification, definition, or rationale is explicitly given.
      
      Ex. "It's a tool, and just like other tools (say automobiles, guns, and
      chain saws), people can use it constructively and destructively, wisely
      and wastefully." [Responding/Explaining/Content]

   3. Opining: This is identical to Bellack et al.'s definition of Opining.

   4. Performing: The Mechanism of Performing is similar to Bellack et al.'s
      instructional-logical meanings of Performing and Directing, in which one
      requests or expects an action to occur. Quite simply, Performing is the
      process of telling someone to do something. 

      Ex. "When you are finished with the student biography, pass them towards
      the center, please." [Eliciting/Performing/Action]

   5. Repeating: Hillman's own words are required for this one: 
      The definition of Repeating is similar to that of Bellack et al. in which
      one (in their case, presumably the teacher) repeats or rephrases what is
      said (presumably by a student) as a way to indicate "an implicit
      admitting" that the offered response was correct. An illustration from the
      FTF transcripts:

      Teacher: Now remember, the output of analysis is the input to--
      [Eliciting/Performing/Content] Student: To design.
      [Responding/Fact-Stating/Content]
   
      Teacher: To design. What else do you need to know?
      [Responding/Repeating/Content, Eliciting/Fact-Stating/Content]

      My coding system, however, has broadened this definition to also include
      repetition used for the purposes of setting context, which is not
      necessarily an indication of agreement. In this example, the use of
      repeating isn't merely to show one agrees (in the sense that the student
      is correct), but it is also used for getting attention -- as a point of
      focus -- to provide context for actions to follow. In this case, the
      context is "You say 'design.' I acknowledge your answer, and use it as a
      point of focus or context for my next move." This is also used in
      asynchronous communications, such as USENET newsgroups or courses
      delivered via CMC, in which text is quoted so that other participants will
      understand what the respondent is talking about.

   6. Rating: A combination of Bellack's Rating, and Acknowledgment. This
      serves to appraise or acknowledge a participant's move.
      
      Ex. "He's right." [Responding/Rating/Person]

   7. Rhetorical Device: an Eliciting move that is /not intended/ to solicit a
      response. This can be a graphic or some other prop used in the classroom.
      A rhetorical device may be used in a series of Lecturing or Fact-Stating
      moves for such a purpose. A rhetorical question would be an eliciting
      purpose in conjunction with a rhetorical device mechanism.
      
      Ex. See Hillman's thesis for a detailed example.

   8. Filler: Analogous with the Idling Purpose, but for mechanisms.

   9. Not Clear: The bottom value.
** Subject
   This tier describes /what/ is being discussed in the sentence, the content
   being considered or statements /about/ something.

   1. Person: The subject of a sentence is literally a person.

      Ex. "I was pleased to have the opportunity to get to know you a bit
      through my role as Client in the Systems Analysis course Case Study."
      [Lecturing/Opining/Person]

   2. Action: a person or object does something, this definition includes
      Bellack et al.'s definition of Action.
      
      Ex. "Those of you who do not have books, look on."
      [Eliciting/Performing/Action]

   3. Procedure: A subset of Action, in which one is told /how/ to do something,
      rather than just /to do/ something.
      
      Ex. "If you've already made a new replica of the User's Guide, please do
      not replicate it further until the above mentioned posting."
      [Eliciting/Performing/Procedure]

   4. Content: This code is used for sentences related to course content. This
      is Bellack's Substantive Meaning category, except that instead of defining
      it in terms of the specific content of the subject, it is defined as being
      /on-topic/. If a sentence refers to the /subject/ of the course, then it
      is /on-topic/, and is Content.
      
      Ex. "With relational, you basically retrieve multiple records at a single
      time and the system decides how to access based on your call."
      [Lecturing/Explaining/Content]

   5. Supplies: The subject of the sentence deals with course material, teaching
      aids, and devices, be they books, forms, projectors, computers etc..
      
      Ex. "This tape is about three years old." [Lecturing/Fact-Stating/Supplies]

   6. Not Clear: The bottom value for the Supply tier.
** Handling Combined moves
   If a sentence encompasses more than one subject, it is coded as the highest
   appropriate level. Thus, to use Bellack et al.'s example, a teacher directing
   students to engage in some classroom procedure which required the use of
   supplies would be coded as Procedure-Supplies. The rationale is that to have
   the course, one must have students (Person). These students may be directed
   (Action) to engage in some classroom Procedure (Procedure) which required the
   use of Supplies (Supplies).

* References that will be of use and why
  1. Paper: Weber, R. P. (1985). Basic content analysis. Beverly Hills: Sage
     Publications.

     Why: This paper defines and describes general steps to classify a text into
     categories of content.

  2. Paper: Atkinson, P. (1981). Inspecting classroom talk. In C. Adelman (Ed.),
     Uttering, muttering: Collecting, using and reporting talk for social and
     educational research, (pp. 98-113). London: Grant McIntyre Ltd. 

     Why: This paper explains that, the ability to respond, and participate in
     interactions, in synchronous communication, is made possible by the /typing/
     of utterances that immediately precede that one.

  3. Paper: Sacks, H., Schegloff, E., & Jefferson, G. (1974). A simplest
     systematics for the organisation of turn-taking for conversation. Language,
     50, 696-735.

     Why: This paper expands on Atkinson's paper by describing interactions as
     an adjacency pair.


* Other thoughts
  1. Bellack's system is synchronous i.e. based on discourse and inter-locution.
     Computer based learning artifacts are asynchronous i.e. one sided exegeses.
     The DSL we are trying to make is...synchronous? or asynchronous, I'm
     pretty sure we discussed this as synchronous.
